// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caiqnbdyzogujspdbifk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhaXFuYmR5em9ndWpzcGRiaWZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MTEwNzIsImV4cCI6MjA2NTM4NzA3Mn0.VKcfmbNXUz2_qnbJ6fS9rBY3NtEzk9-L4O9Nfz9kNYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);